name: React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stop all containers
        run: docker-compose down

      - name: Build React Container
        run: docker-compose up -d --build

      - name: Wait containers
        run: sleep 30s

      - name: Set Laravel Env Key
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          docker cp .env cloud-laravel:/app
      
      - name: Generate Laravel key
        run: docker exec cloud-laravel php artisan key:generate

      - name: Test React
        run: docker exec cloud-react npm run test

      - name: Test Laravel
        run: docker exec cloud-laravel php artisan test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install openssh-client -y

      - name: Copy code to server
        run: ssh -i ${{ secrets.CONTABO }} root@31.220.81.184

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/cloud
            # Add any additional deployment steps here
