name: React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react_tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6381:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stop all containers
        run: docker-compose down

      - name: Build React Container
        run: docker-compose up -d --build

      - name: Wait containers
        run: sleep 30s

      - name: Test react
        run: docker exec cloud-react npm run test

      - name: Test laravel
        run: docker exec cloud-laravel php artisan test

