name: Run tests in docker

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run tests in docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: adambirds/docker-compose-action@v1.3.0
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            laravel
            react
          test-container: laravel
          test-command: "php artisan test"
      - name: Check containers
        run: docker-compose logs