name: Run Jest tests

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Run Jest tests
    runs-on: ubuntu-latest

    services:
      react:
        image: node
        ports:
          - 3000:3000
        options: --name react

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and run React app in Docker
        run: docker build -t my-react-app frontend
      - name: Build and run React app in Docker
        run: docker run -d --name my-react-container -p 3000:3000 my-react-app

      - name: Wait for React app to start
        run: sleep 30s

      - name: Run Jest tests
        run: docker exec my-react-container npm test

      - name: Stop and remove React container
        run: docker stop my-react-container && docker rm my-react-container