name: React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react_tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6381:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Stop all containers
        run: docker-compose down

      - name: Build React Container
        run: docker-compose up -d --build

      - name: Wait containers
        run: sleep 30s

      - name: Set Laravel Env Key
        run: |
          echo "APP_KEY=base64:$(openssl rand -base64 32)" > .env
          docker cp .env cloud-laravel:/path/to/your/laravel/project
      
      - name: Generate Laravel key
        run: docker exec cloud-laravel php artisan key:generate

      - name: Test React
        run: docker exec cloud-react npm run test

      - name: Test Laravel
        run: docker exec cloud-laravel php artisan test

