name: React Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  react_tests:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6381:6379

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build React Container
        run: docker-compose -f docker-compose.yaml build react

      - name: Start React Container
        run: |
          docker-compose -f docker-compose.yml build react
          docker-compose -f docker-compose.yml up -d react
          docker-compose -f docker-compose.yml exec -T react ./node_modules/.bin/react-scripts start

      - name: Wait for React to be ready
        run: docker-compose -f docker-compose.yaml exec -T react /bin/bash -c "while ! nc -z localhost 3000; do sleep 1; done;"

      - name: Install Node Modules
        run: docker-compose -f docker-compose.yaml exec -T react npm install

      - name: Run React Tests
        run: docker-compose -f docker-compose.yaml exec -T react npm test
